regirstration checket
SVDevelop/js-forms pull request #3
Opened 2018-06-11 17:19 UTC by VSergeyV

2018-06-13 09:07 UTC, nobleworkshop commented on registration.html
>  			<div class="error-description">
Этот блок с ошибкой виден сразу при открытии страницы. А должен быть скрыт.

2018-06-13 09:08 UTC, nobleworkshop requested changes
Все верно, только нужно скрыть блок с ошибками.

2018-06-13 11:00 UTC, VSergeyV commented
Исправил

2018-06-15 20:52 UTC, nobleworkshop requested changes
Тоже самое что и с логином.

2018-06-15 22:37 UTC, merged