login check
SVDevelop/js-forms pull request #4
Opened 2018-06-11 18:18 UTC by VSergeyV

2018-06-13 09:02 UTC, nobleworkshop commented on login.html
>  			<div class="error-description">
Этот блок с ошибкой виден сразу при открытии страницы. А должен быть скрыт.

2018-06-13 09:06 UTC, nobleworkshop requested changes
Все верно, только нужно скрыть блок с ошибками.

2018-06-13 11:01 UTC, VSergeyV commented
Исправил

2018-06-15 20:50 UTC, nobleworkshop commented
Сейчас отображается вот этот блок: 
![image](https://user-images.githubusercontent.com/12967597/41488968-e7474058-70f6-11e8-9b4f-244167b93e66.png)

2018-06-15 20:51 UTC, nobleworkshop requested changes
Сделай плиз мерж в develop комментариев, логина и регистрации. И проверь чтобы все хорошо работало. И блоки с ошибками не отображались при открытии страницы. После жду pull request

2018-06-15 22:39 UTC, merged